# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-14 14:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nc', '0055_auto_20181008_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='num_accounts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='asset',
            name='account_trusters',
            field=models.ManyToManyField(blank=True, related_name='assets_trusting', to='nc.Account'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='trusters',
            field=models.ManyToManyField(blank=True, related_name='assets_trusting', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='profiles_following', to=settings.AUTH_USER_MODEL),
        ),
    ]
