# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-17 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nc', '0057_auto_20181017_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_id',
            field=models.CharField(default=None, max_length=36),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='verb',
            field=models.IntegerField(choices=[(0, 'post'), (1, 'send'), (2, 'issue'), (3, 'trust'), (4, 'offer'), (5, 'follow'), (6, 'comment')], default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='activity_id',
            field=models.CharField(default=None, max_length=36),
            preserve_default=False,
        ),
    ]
