# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-17 03:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nc', '0058_auto_20181017_0205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.CharField(max_length=64)),
                ('xlm_value', models.FloatField(default=0.0)),
            ],
        ),
        migrations.RemoveField(
            model_name='reward',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='user',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='rewarded_by',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='rewarded_by',
        ),
        migrations.DeleteModel(
            name='Reward',
        ),
        migrations.AddField(
            model_name='award',
            name='activity',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='nc.Activity'),
        ),
        migrations.AddField(
            model_name='award',
            name='comment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='nc.Comment'),
        ),
        migrations.AddField(
            model_name='award',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards_given_out', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='awarded_by',
            field=models.ManyToManyField(blank=True, related_name='activities_awarded', through='nc.Award', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='awarded_by',
            field=models.ManyToManyField(blank=True, related_name='comments_awarded', through='nc.Award', to=settings.AUTH_USER_MODEL),
        ),
    ]
