# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-18 17:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nc', '0059_auto_20181017_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='commented_by',
            field=models.ManyToManyField(blank=True, related_name='activities_commented_on', through='nc.Comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
