# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-18 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nc', '0061_auto_20181018_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_awards_default',
            field=models.BooleanField(default=False),
        ),
    ]
