# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-18 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nc', '0062_account_is_awards_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_awards_default',
        ),
        migrations.AddField(
            model_name='profile',
            name='awards_default_account',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='nc.Account'),
        ),
    ]
