# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-19 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nc', '0065_profile_default_xlm_award_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='allow_comment_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='allow_post_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_id',
            field=models.CharField(blank=True, default=None, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='activity_id',
            field=models.CharField(blank=True, default=None, max_length=36, null=True),
        ),
    ]
