# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-19 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nc', '0066_auto_20181019_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='default_xlm_award_amount',
            field=models.FloatField(default=1.0),
        ),
    ]
