# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-19 22:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nc', '0067_auto_20181019_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.CharField(max_length=64)),
                ('xlm_value', models.FloatField(default=0.0)),
            ],
        ),
        migrations.RemoveField(
            model_name='award',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='award',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='award',
            name='user',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='default_award_account',
            new_name='default_reward_account',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='default_xlm_award_amount',
            new_name='default_xlm_reward_amount',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='awarded_by',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='awarded_by',
        ),
        migrations.DeleteModel(
            name='Award',
        ),
        migrations.AddField(
            model_name='reward',
            name='activity',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='nc.Activity'),
        ),
        migrations.AddField(
            model_name='reward',
            name='comment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='nc.Comment'),
        ),
        migrations.AddField(
            model_name='reward',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards_given_out', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='rewarded_by',
            field=models.ManyToManyField(blank=True, related_name='activities_rewarded', through='nc.Reward', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='rewarded_by',
            field=models.ManyToManyField(blank=True, related_name='comments_rewarded', through='nc.Reward', to=settings.AUTH_USER_MODEL),
        ),
    ]
