# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-22 05:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nc', '0068_auto_20181019_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='issuer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='assets_issued', to='nc.Account'),
        ),
    ]
