# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-08 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nc', '0069_auto_20181022_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='conditions',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
